# Generated by Django 5.0.7 on 2024-08-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_userprofile_city_userprofile_pin_userprofile_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
    ]
