# Generated by Django 5.0.7 on 2024-08-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurantstaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
