# Generated by Django 5.0.7 on 2024-08-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_deliveryuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryUser',
        ),
    ]
