# Generated by Django 5.0.7 on 2024-08-11 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryusers', '0001_initial'),
        ('restaurant', '0007_delete_deliveryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryuser',
            name='restaurant',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryuser',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
